# Generated by Django 5.2.3 on 2025-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_description_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
